### ISSUE TITLE
Non 200 response from API call causes Go Lambda execution to exit prematurely

### ISSUE THREAD

**Issue by tkidd77** [lambci/docker-lambda#226] opened 2019-11-21 20:47 UTC
https://github.com/lambci/docker-lambda/blob/a86ac3b3a6f761ea17366b82eb30f6607dad3572/go1.x/run/aws-lambda-mock.go#L331-L334

I have a Go Lambda in which I am using the [Resty](https://github.com/go-resty/resty) package to hit an API where I expect a non `200` return. Upon receiving this return, the Lambda execution exits prematurely without even returning anything to the handler. The `error` return from the Resty client is `nil`. If the Resty client receives a `200` the Lambda executes without issue.

Lambda execution stops with `Non 202 status code from local server` as per above while running my Lambda in the lambci/lambda:go1.x container.

While the referenced code above is catching the non 202 return, the underlying issue is likely elsewhere in the container/ lambda server.

**Comment by mhart** [comment] 2019-11-21 20:54
Hmmm. That's weird. Is your API running locally on port 9001 by any chance? If not, the only thing I can think is that something like this is being hit: https://github.com/lambci/docker-lambda/blob/a86ac3b3a6f761ea17366b82eb30f6607dad3572/provided/run/init.go#L449-L452

What do you do when you get non-200 responses? Anything special/unusual?

I can add some more debugging code in there to determine what status code was actually returned by the local server, and what the body is.

**Comment by mhart** [comment] 2019-11-21 20:55
(if you could create a small repro, that would be awesome obviously)

**Comment by tkidd77** [comment] 2019-11-21 21:04
Nothing running on port 9001. Nothing special after I see my 400 response.
```
if err != nil && resp.RawResponse.StatusCode == 400 {
		return "", nil
	}
```

**Comment by mhart** [comment] 2019-11-21 21:17
You're returning an empty string – that's interesting. I wonder if the API's blowing up on that (because it's not valid JSON)

Does that work fine on Lambda? If so I might need to allow for that

**Comment by tkidd77** [comment] 2019-11-21 21:19
```
type somestruct struct {
	Name string
}
var simple *somestruct
simple.Name = "Tim"
return simple, nil
```
results in `Non 202 status code from local server`

```
type somestruct struct {
	Name string
}
var simple *somestruct
// simple.Name = "Tim"
return simple, nil
```
results in the expected `null`.

**Comment by tkidd77** [comment] 2019-11-21 21:22
```
// type somestruct struct {
// 	Name string
// }
// var simple *somestruct
// simple.Name = "Tim"
return "", nil
```
results in the expected `""`.

**Comment by tkidd77** [comment] 2019-11-21 21:23
I don't know of an empty string being an issue on Lambda

**Comment by mhart** [comment] 2019-11-21 21:28
Awesome, have reproduced – looking into it now, thanks!

**Comment by mhart** [comment] 2019-11-21 21:37
So I think it's when Lambda's trying to return an error. The problem is I'm not converting the stack trace correctly.

The error it's trying to return is: `runtime error: invalid memory address or nil pointer dereference`

**Comment by mhart** [comment] 2019-11-21 21:57
Alrighty, all fixed now! Errors should be reported correctly now – thanks for letting me know 👍

**Closed** 2019-11-21 21:56 UTC

**Comment by tkidd77** [comment] 2019-11-21 22:03
Confirmed, thanks for the quick resolution!
