### ISSUE TITLE
Unable to use yum command in lambci/lambda-base

### ISSUE THREAD

**Issue by jackwarner** [lambci/docker-lambda#11] opened 2016-10-19 18:11 UTC
I've created a Dockerfile built from lambci/lambda-base so I can add some custom commands to speed up developer workflow.

We'd like to install git on the image, but when I run: 

yum install git

I get:

http://packages.us-east-1.amazonaws.com/2015.09/main/201509419456/x86_64/repodata/repomd.xml?instance_id=fail&region=timeout: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 403 Forbidden"
Trying other mirror.
http://packages.us-west-1.amazonaws.com/2015.09/main/201509419456/x86_64/repodata/repomd.xml?instance_id=fail&region=timeout: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 403 Forbidden"
Trying other mirror.
http://packages.us-west-2.amazonaws.com/2015.09/main/201509419456/x86_64/repodata/repomd.xml?instance_id=fail&region=timeout: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 403 Forbidden"
Trying other mirror.
http://packages.eu-west-1.amazonaws.com/2015.09/main/201509419456/x86_64/repodata/repomd.xml?instance_id=fail&region=timeout: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 403 Forbidden"
Trying other mirror.
http://packages.eu-central-1.amazonaws.com/2015.09/main/201509419456/x86_64/repodata/repomd.xml?instance_id=fail&region=timeout: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 403 Forbidden"
Trying other mirror.
http://packages.ap-southeast-1.amazonaws.com/2015.09/main/201509419456/x86_64/repodata/repomd.xml?instance_id=fail&region=timeout: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 403 Forbidden"
Trying other mirror.
http://packages.ap-northeast-1.amazonaws.com/2015.09/main/201509419456/x86_64/repodata/repomd.xml?instance_id=fail&region=timeout: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 403 Forbidden"
Trying other mirror.
http://packages.sa-east-1.amazonaws.com/2015.09/main/201509419456/x86_64/repodata/repomd.xml?instance_id=fail&region=timeout: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 403 Forbidden"
Trying other mirror.
http://packages.ap-southeast-2.amazonaws.com/2015.09/main/201509419456/x86_64/repodata/repomd.xml?instance_id=fail&region=timeout: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 403 Forbidden"
Trying other mirror.

 One of the configured repositories failed (amzn-main-Base),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable amzn-main

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=amzn-main.skip_if_unavailable=true

failure: repodata/repomd.xml from amzn-main: [Errno 256] No more mirrors to try.

yum-config-manager is not available.

Thanks!

**Comment by mhart** [comment] 2016-10-19 19:23
Hi @jackwarner! This is a dupe of https://github.com/lambci/docker-lambda/issues/10#issuecomment-248608294 – tldr; you need to be running on EC2 if you want to access Amazon's yum repos

**Closed by mhart** 2016-10-19 19:23 UTC
