### ISSUE TITLE
Issue with processes spawning sub-processes in AWS Lambda not replicable in docker-lambda

### ISSUE THREAD

**Issue by alessbelli** [lambci/docker-lambda#112] opened 2018-08-24 10:41 UTC
I just encountered a weird problem with chromium (actually [chrome-headless](https://github.com/adieuadieu/serverless-chrome)) and [pyppeteer](https://github.com/miyakogi/pyppeteer/) (that python port of puppeteer, which only occurred on AWS and I could not replicate in docker-lambda.

When I used pyppeteer to drive a chrome process in --headless mode, the browser would launch, and properly communicate with pyppeteer, however it would not respond to instructions to open a page (ie: a tab), and silently froze the entire lambda until timing out. [issue here](https://github.com/adieuadieu/serverless-chrome/issues/161)
It was solved by adding a --single-process flag to chromium on launch, which would seem to point out to this cause, therefore I think that this maybe is 'expected' behavior on a Lambda (however undocumented?) but docker-lambda does not have this limitation, so it would be nice to add the same limitation for better testing :)

**Comment by mhart** [comment] 2018-10-03 15:38
@alessbelli how did you go with this?

**Comment by DinisCruz** [comment] 2018-11-15 11:01
If it helps others, here is how I was able to do it : https://twitter.com/DinisCruz/status/1063023374920769542

**Comment by mhart** [comment] 2019-01-02 20:53
@alessbelli going to close this because I'm like 90% sure you could reproduce the behaviour by using the above command line, but let me know if you can't

**Closed by mhart** 2019-01-02 20:53 UTC
