### ISSUE TITLE
No Python3 headers in build-python3.6 image

### ISSUE THREAD

**Issue by nicholasbishop** [lambci/docker-lambda#33] opened 2017-05-03 23:50 UTC
The `build-python3.6` image seems to be missing headers for Python3:

```
$ sudo docker run lambci/lambda:build-python3.6 find / -iname '*python*.h'
/usr/include/python2.7/pythonrun.h
/usr/include/python2.7/Python-ast.h
/usr/include/python2.7/Python.h
```

Yum only shows packages for Python 3.4, not 3.6:

```
$ sudo docker run lambci/lambda:build-python3.6 yum search python3
============================= N/S matched: python3 =============================
mod24_wsgi-python34.x86_64 : A WSGI interface for Python web applications in
                           : Apache
postgresql92-plpython27.x86_64 : The Python3 procedural language for PostgreSQL
python34.x86_64 : Version 3.4 of the Python programming language aka Python 3000
python34-devel.x86_64 : Libraries and header files needed for Python 3.4
                      : development
python34-docs.noarch : Documentation for the Python programming language
python34-libs.i686 : Python 3.4 runtime libraries
python34-libs.x86_64 : Python 3.4 runtime libraries
python34-pip.noarch : A tool for installing and managing Python packages
python34-setuptools.noarch : Easily build and distribute Python packages
python34-test.x86_64 : The test modules from the main python 3.4 package
python34-tools.x86_64 : A collection of tools included with Python 3.4
python34-virtualenv.noarch : Tool to create isolated Python environments

  Name and summary matches only, use "search all" for everything.
```

**Comment by mhart** [comment] 2017-05-04 19:32
This is basically a duplicate of #32 – see https://github.com/lambci/docker-lambda/issues/32#issuecomment-299286053 for more details

**Closed by mhart** 2017-05-04 19:32 UTC
