### ISSUE TITLE
.NET Core 2.1 Unable to use Microsoft.AspNetCore.App/All

### ISSUE THREAD

**Issue by adfinlay** [lambci/docker-lambda#177] opened 2019-04-05 13:02 UTC
Per https://aws.amazon.com/blogs/developer/serverless-asp-net-core-2-0-applications/ it is recommended that you reference `Microsoft.AspNetCore.All` (or `.App`) to reduce the deployment package size and cold start time of C# .NET Core lambda functions. This means that the .NET Core dll files aren't packaged as part of the deployment, but instead use the "Runtime package store" (https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store).  

The AWS blog post I mentioned says "However, it doesn’t include them in the deployment package because they’re already available in Lambda."

I've been trying to troubleshoot `AWSLambda.Internal.Bootstrap.LambdaValidationException: Unable to load type 'Lambda.LambdaEntryPoint' from assembly 'Lambda'` and realised that it works fine when I remove the dependency on `Microsoft.AspNetCore.App` and add the `AspNetCore` dependencies one by one (i.e. it is breaking because the .NET Core dlls aren't available).

Is there any way to make the lambda environment in this container have the package store available so that we can continue to use the metapackage AND test locally?

**Comment by mhart** [comment] 2019-04-05 13:07
If there's a difference between behavior that you see when running your zip on a live AWS Lambda, and what you see when running on a docker-lambda run container, then I'm happy to look into it – but in terms of adding things to the run container, that would break the idea that the containers are intended to be a faithful representation of the live environment. Otherwise ppl will assume they can do things and link to things that actually don't exist.

**Comment by adfinlay** [comment] 2019-04-05 13:20
> If there's a difference between behavior that you see when running your zip on a live AWS Lambda, and what you see when running on a docker-lambda run container

That is the case here. If I reference `Microsoft.AspNetCore.App` then the zip that is deployed to lambda doesn't contain the .NET dlls, and the lambda function works 100% on AWS Lambda as (per AWS in the blog article I linked) "Adding this dependency makes all of the ASP.NET Core packages and Entity Framework Core packages available to your application. However, it doesn’t include them in the deployment package because they’re already available in Lambda."

**Comment by mhart** [comment] 2019-04-05 14:05
Ok, we'll need to figure out why they're not being linked to then – because they should exist on the image in the same place they do on Lambda itself.

The .NET bootstrap is unfortunately the most complicated of the languages, because of the way that Lambda instantiates the runtime – would love to triage any library linking issues.

**Comment by adfinlay** [comment] 2019-04-19 13:50
Maybe I'm heading in the wrong direction here, but from release notes like [this](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.201-sdk-download.md#aspnet-runtime-core-package-store): 

> The Runtime Package Store is installed by the .NET Core SDK 

But the output from `dotnet --info` in the container is:

```
bash-4.2# dotnet --info

Host (useful for support):
  Version: 2.1.6-servicing-27105-0
  Commit:  be138ea40c

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/var/lang/bin/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/var/lang/bin/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/var/lang/bin/shared/Microsoft.NETCore.App]

```

Is it the fact that the SDK isn't installed perhaps? From what I can tell the Runtime Package Store should be installed at `<dotnet installation dir>/store`.

**Comment by adfinlay** [comment] 2019-04-22 13:33
I set up VS Code and configured debugging, and it seems that a `FileNotFoundException` is being thrown when trying to load `/var/task/Microsoft.AspNetCore.Hosting.Abstractions.dll`. I'm guessing that this is from https://github.com/lambci/docker-lambda/blob/master/dotnetcore2.1/run/MockBootstraps/Program.cs#L92 but the file isn't at that location because it should be linked to from the runtime.

**Comment by mhart** [comment] 2019-04-22 14:06
@adfinlay if you can give more detail as to how that DLL is resolved on Lambda itself, that might help with figuring out a resolution.

I can see that the file is located at `/var/lang/bin/shared/Microsoft.AspNetCore.App/2.1.8/Microsoft.AspNetCore.Hosting.Abstractions.dll`

But it would be very brittle to add that path specifically to the Assembly resolver (ie, if the version changes)

If not sure if this directory (and others like it) are added to the Global Assembly Cache – and if so, how they're added.

**Comment by adfinlay** [comment] 2019-04-22 14:23
There is no GAC as such in .NET core 2.x, but there are a few special metapackages (like Microsoft.AspNetCore.App) that use the shared framework files instead of including the dlls in the package (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.1).

From reading through that page (and the linked page https://docs.microsoft.com/en-us/dotnet/core/build/distribution-packaging) the shared framework at `<dotnet install dir>/shared/Microsoft.AspNetCore.App/<aspnetcore version>` should automatically be used.

**Comment by mhart** [comment] 2019-04-22 14:29
What's odd is that `/var/lang/bin/dotnet --info` reports `Version: 2.1.9-servicing-27413-0`

Whereas all of the DLLs are version 2.1.8

I'm not sure if that makes a difference?

In any case, `/var/lang/bin/shared/Microsoft.AspNetCore.App/2.1.8` definitely exists on `docker-lambda`

**Comment by junderhill** [comment] 2019-10-17 08:49
I'm having this exact issue as well. I have the code running successfully in AWS however using 
`sam local start-api` and then trying to invoke one of the end points results in this error
```
Unhandled exception occured in runner:
AWSLambda.Internal.Bootstrap.LambdaValidationException: Unable to load type 'Test.LambdaEntryPoint' from assembly 'Test'.
   at AWSLambda.Internal.Bootstrap.UserCodeLoader.Init(Action`1 customerLoggingAction) in /opt/workspace/LambdaSandboxCoreCLR-2-1/src/Bootstrap/UserCodeLoader.cs:line 122
   at MockLambdaRuntime.Program.Main(String[] args) in /source/Program.cs:line 51
```

Don't suppose anyone has been able to progress this issue?

**Comment by mhart** [comment] 2019-10-17 16:54
So I think the issue stems from the fact that on production Lambda, dotnet is executed like so:

```
dotnet exec \
  --depsfile /var/task/HelloWorld.deps.json \
  --runtimeconfig /var/task/HelloWorld.runtimeconfig.json \
  /var/runtime/Bootstrap.dll \
  --invokeid d4b8ee9a-7bb4-4940-bfb6-33c2def9c023 \
  --flag 0 \
  --handler HelloWorld::HelloWorld.Function::FunctionHandlerAsync \
  --errorcode
```

Whereas in the docker environment we just execute:

```
dotnet /var/runtime/MockBootstraps.dll
```

And dynamically load the handler assembly, etc

Now, `dotnet exec` isn't documented AFAICT – but the way it uses the handler's depsfile and runtimeconfig is something that I'm not entirely sure how to replicate.

One option would be to completely recompile Bootstrap.dll instead of just referencing it from MockBootstraps, but that's a rather large step.

The quick hacky fix I can think of would be to try and search `/var/lang/bin/shared/Microsoft.AspNetCore.App/<dotnetversion>/` for the assembly in question when it's trying to be loaded

Any .NET Core experts here would be very helpful

**Comment by mhart** [comment] 2019-10-17 17:54
Ok, I think I've fixed this by just including `Microsoft.AspNetCore.App` as a `PackageReference` in https://github.com/lambci/docker-lambda/commit/13fb330121d82fa87792c358137c80866bbeaa5f

I'm going to close this, but feel free to reopen if you're seeing it for other packages

**Closed by mhart** 2019-10-17 17:54 UTC

**Comment by mhart** [comment] 2019-10-17 19:30
Changed to `Microsoft.AspNetCore.All` instead as that includes `Microsoft.AspNetCore.App`

**Comment by Nevett** [comment] 2019-10-18 14:47
I am having builds fail on CI now that I think are due to this issue. It started happening overnight, and I see that a new version of the container was released over this time. To be clear, commits from weeks ago that succeeded now fail to run through `sam` test suites as of today. There are very few dependencies that we don't have pinned to specific versions which is what led me here.

The error we see is

> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
File name: 'Microsoft.Extensions.Configuration.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at AWSLambda.Internal.Bootstrap.UserCodeLoader.Init(Action`1 customerLoggingAction) in /opt/workspace/LambdaSandboxCoreCLR-2-1/src/Bootstrap/UserCodeLoader.cs:line 119
   at MockLambdaRuntime.Program.Main(String[] args) in /source/Program.cs:line 51

Here are the dependencies used by my project
![image](https://user-images.githubusercontent.com/1307200/67104253-850fdb80-f1be-11e9-8a87-fedb8a961e70.png)

**Comment by mhart** [comment] 2019-10-18 14:49
Ugh, I'm sorry about that – I'll see if I can look into it today. Figuring out how the system deals with dependencies on .NET really is an opaque minefield.

**Comment by mhart** [comment] 2019-10-18 14:50
To be clear, you'd not shipping `Microsoft.Extensions.Configuration.Abstractions.dll` in your lambda zip 
bundle are you?

**Comment by mhart** [comment] 2019-10-18 14:53
Btw, if you can give me a small reproduction of this (as a zip, like in https://github.com/lambci/docker-lambda/issues/177#issuecomment-525858866 , that would be VERY helpful)

**Comment by Nevett** [comment] 2019-10-18 15:03
Hi, thanks for the quick replies!

I've shipped one of our builds that was failing `sam` tests to AWS to test. The function runs fine on AWS. 

The built bundle _does_ include `Microsoft.Extensions.Abstractions.dll`, which is also present (as you'd expect) in the published folder that the template is using when `sam` is executing

**Comment by kawaic** [comment] 2019-10-18 15:18
Thank you for the quick look into this, breaking our CI as well.  I'm getting the exact same problem running inside `localstack`. 

`Unhandled exception occured in runner:
AWSLambda.Internal.Bootstrap.LambdaUserCodeException: An exception was thrown when the constructor for type 'Fleet.Lambda.Handlers.VehicleActivityIntervalUpdateHandler' was invoked. Check inner exception for more details. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at AWSLambda.Internal.Bootstrap.UserCodeLoader.GetCustomerObject(Type customerType) in /opt/workspace/LambdaSandboxCoreCLR-2-1/src/Bootstrap/UserCodeLoader.cs:line 733
   --- End of inner exception stack trace ---
   at AWSLambda.Internal.Bootstrap.UserCodeLoader.GetCustomerObject(Type customerType) in /opt/workspace/LambdaSandboxCoreCLR-2-1/src/Bootstrap/UserCodeLoader.cs:line 741
   at AWSLambda.Internal.Bootstrap.UserCodeLoader.Init(Action`1 customerLoggingAction) in /opt/workspace/LambdaSandboxCoreCLR-2-1/src/Bootstrap/UserCodeLoader.cs:line 132
   at MockLambdaRuntime.Program.Main(String[] args) in /source/Program.cs:line 51`

checked that `Microsoft.Extensions.Configuration.Abstractions.dll` is published

**Comment by mhart** [comment] 2019-10-18 15:28
I've just pushed up a new dotnetcore2.1 image with a different approach to assembly loading – let me know if it fixes your problems!

**Comment by Nevett** [comment] 2019-10-18 15:45
The tests pass 🎉 

Thanks for the quick fix!

**Comment by kawaic** [comment] 2019-10-18 16:59
Thank you!!!!
