### ISSUE TITLE
Question: Could this image be running on ARM ?

### ISSUE THREAD

**Issue by philiiiiiipp** [lambci/docker-lambda#267] opened 2020-04-23 13:54 UTC
AWS realeased quite cost efficient [ARM](https://aws.amazon.com/ec2/instance-types/a1/) instances a while ago.

I am wondering if the images here should be able to run there ? If I am trying to run it I get a `standard_init_linux.go:211: exec user process caused "exec format error"` error:

```bash
Running with gitlab-runner 12.3.0 (a8a019e0)
  on aws-runner-default-spot cLQbpDYG
Using Docker executor with image lambci/lambda:build-nodejs12.x ...
Pulling docker image lambci/lambda:build-nodejs12.x ...
Using docker image sha256:347acc023569347c92e38d5ac8412bfe61bdb947ca77f41fb07002031ae54cb9 for lambci/lambda:build-nodejs12.x ...
Running on runner-cLQbpDYG-project-20-concurrent-0 via runner-clqbpdyg-gitlab-docker-machine-1587649444-7c77350f...
Fetching changes..
....
....
Checking out f5f25575 as test_aws...

Skipping Git submodules setup
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
ERROR: Job failed: exit code 1
```

I am not entirely sure if that is because of the docker-lambda image, is this one build for x86 ? And if so, do you think it would be technically possible to make them run on ARM ?

**Comment by mhart** [comment] 2020-04-23 14:22
Dupe of #248 (TLDR; no, not possible at all – Lambda runs on x86 and until AWS releases Lambda for ARM, it won't be possible to create images for it)

**Closed by mhart** 2020-04-23 14:22 UTC

**Comment by sirjla** [comment] 2021-11-17 16:05
Now that lambda has official support for ARM (https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/) can this be reviewed?
