### ISSUE TITLE
No perms to run on 80

### ISSUE THREAD

**Issue by steadysupply** [lambci/docker-lambda#253] opened 2020-02-25 14:55 UTC
Hello,

This project looks really useful for carrying out local integration tests on AWS Lambda functions without resorting to Amazon's dreadful developer tooling.

I've got what looks like a handy looking little setup running using Docker Compose, with a handful of containers each running its own Lambda. I'm going to be invoking them from another container running in the virtual network created by Docker Compose and don't need port mappings on the host machine.

I'm using the Python build/run images and everything works fine so far (even using the `boto3` library to invoke Lambdas in other containers using a custom `endpoint_url`). The only bugbear I've got is as follows. Since I don't need port mappings, I'd like to have the "waiting for requests" service to be running on port `80` on each container.

However, when I set `DOCKER_LAMBDA_API_PORT` and `DOCKER_LAMBDA_RUNTIME_PORT` to `80`, I get permission denied errors:
```
$ docker-compose --project-directory . -f docker/compose.yml up handle inbound outbound
Recreating demo_handle_1   ... done
Recreating demo_inbound_1  ... done
Recreating demo_outbound_1 ... done
Attaching to demo_handle_1, demo_outbound_1, demo_inbound_1
demo_inbound_1 | 2020/02/25 14:51:22 listen tcp 127.0.0.1:80: bind: permission denied
demo_handle_1 | 2020/02/25 14:51:22 listen tcp 127.0.0.1:80: bind: permission denied
demo_outbound_1 | 2020/02/25 14:51:22 listen tcp 127.0.0.1:80: bind: permission denied
demo_handle_1 exited with code 1
demo_inbound_1 exited with code 1
demo_outbound_1 exited with code 1
```

**Comment by mhart** [comment] 2020-02-25 15:01
That's because you don't have permissions to open up port 80 on your local machine. You'll need to read up on some docker documentation (possible docker compose documentation) on how to expose internal ports on different ports on your host machine

Closing as this isn't an issue with docker-lambda (it would happen with any docker image). Good luck!

**Closed by mhart** 2020-02-25 15:01 UTC

**Comment by mhart** [comment] 2020-02-25 15:05
I did close this rather quickly. Reading again, it might be because the docker user doesn't have permissions to connect to port 80 internally. You can change the user if you like – but keep in mind that this won't be a faithful reproduction of Lambda anymore – because the Lambda user doesn't have permission to open port 80 either

**Comment by mhart** [comment] 2020-02-25 15:26
All containers use the `sbx_user1051` user, which is the same as on Lambda itself (or similar enough – there are a bunch of similar sandbox users): https://github.com/lambci/docker-lambda/blob/master/nodejs12.x/run/Dockerfile#L19

You could specify `user: root` in your docker compose and see if that works

**Comment by steadysupply** [comment] 2020-02-25 16:50
> specify `user: root`

Ah, thanks, that's a neat workaround!

Not wanting to run on port 9001 is just a vanity thing really, meaning I can write eg.

``` py
λ = 'handle'
client = boto3.client("lambda", endpoint_url=f"http://{λ}")
client.invoke(FunctionName=λ, Payload=json.dumps(event))
```

**Comment by mhart** [comment] 2020-02-25 17:26
It's a neat workaround, but as I said, it gives you root access where you wouldn't otherwise have it – so you might find yourself writing to directories which you don't actually have access to on Lambda, etc, etc. Just don't be caught out by it is all.

**Comment by steadysupply** [comment] 2020-02-26 07:19
Yep, gotcha. Hopefully I won't be caught out by my vanity `;)`
