### ISSUE TITLE
Images sometimes don't include ssh-agent

### ISSUE THREAD

**Issue by nunofgs** [lambci/docker-lambda#162] opened 2019-01-31 12:21 UTC
Something odd is going on. I'm using `lambci/lambda:build-nodejs8.10` as a base image and got an error a few days ago:

```
sh: ssh-agent: command not found
```

(My image depends on ssh-agent being included in your base image).

A day later, everything was fine. Pulling `lambci/lambda:build-nodejs8.10` has the correct ssh binaries. Now, today, I'm getting the same thing.

It seems this image is somehow compiling without `ssh` binaries but only sometimes. Maybe a problem in your build trigger?

**Comment by debugwand** [comment] 2019-01-31 14:54
We also seeing this in CircleCI in the checkout step where it tries to get our code from github, which has been happening consistently since this morning.
```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
```

SSHing into the build shows that `git` command works but `ssh` returns command not found

**Comment by scottrmercer** [comment] 2019-01-31 14:55
Same here, also on circleCI, just started this morning as well. We are using Python 3.6, which I did notice was updated yesterday.

**Comment by mhart** [comment] 2019-01-31 15:39
Hmmm, well the build image doesn't *explicitly* include ssh – but instead it installs the `development` group: https://github.com/lambci/docker-lambda/blob/master/base/build/Dockerfile#L20

Lambda has made some changes to the underlying OS recently (which is why I had to rebuild all the images) – I wonder if that's made a difference? Maybe `ssh` is no longer included in the `development` group or something?

I'll look into it

**Comment by killthrush** [comment] 2019-01-31 15:40
Can confirm problem with python 3.6.  This command worked fine yesterday: `docker run --name lambdapy36 -it -v $(shell pwd):/reactor lambci/lambda:build-python3.6 /bin/sh -c "pip install -r /src/requirements.txt -t /src/vendored/"`.  Error message is `fatal: unable to fork` and there is no `ssh` exe on the image.

**Comment by mhart** [comment] 2019-01-31 15:47
Here's what's included in the group – I don't see any `ssh`, so either it's been removed, or it's a dependency of another package that may have changed:
```
$ bash-4.2# yum groupinfo development

Group: Development tools
 Group-Id: development
 Description: A basic development environment.
 Mandatory Packages:
   =autoconf
   =automake
    binutils
   =bison
   =flex
   =gcc
   =gcc-c++
    gdb
   =gettext
   =kexec-tools
   =latrace
   =libtool
    make
    patch
    pkgconfig
    rpm-build
   =strace
   =system-rpm-config
   =systemtap-runtime
 Default Packages:
   =byacc
   =crash
   =cscope
   =ctags
   =cvs
   =diffstat
   =doxygen
    elfutils
   =gcc-gfortran
   =git
   =indent
   =intltool
   =ltrace
   =patchutils
   =rcs
   =subversion
   =swig
   =systemtap
   =texinfo
   =valgrind
 Optional Packages:
   ant
   bzr-python27
   chrpath
   cmake
   dejagnu
   expect
   gcc-gnat
   glibc-utils
   imake
   jpackage-utils
   lslk
   mercurial-python27
   mod_dav_svn
   nasm
   perltidy
   python27-babel
   python27-docs
   rpmdevtools
   rpmlint
   systemtap-initscript
```

**Comment by scottrmercer** [comment] 2019-01-31 15:48
For circleCI, we've worked around the issue by adding the following to our build script:

      - run: yum reinstall -y fipscheck-lib openssh-clients

**Comment by killthrush** [comment] 2019-01-31 15:50
@scottrmercer - that worked for me! cheers!

**Comment by mhart** [comment] 2019-01-31 15:51
I'll add this to the base image build too – no idea what happened, unfortunately I haven't had much communication from AWS over the OS changes. Sorry y'all.

**Comment by killthrush** [comment] 2019-01-31 15:54
No worries @mhart - thanks for responding so quickly!

**Comment by mhart** [comment] 2019-01-31 19:22
Ok, as of https://github.com/lambci/docker-lambda/commit/4eaedc31dd2a6c3a14e68e8b989f19a86a121347 this should be fixed. Let me know if y'all run into any more issues!

**Closed by mhart** 2019-01-31 19:22 UTC

**Comment by killthrush** [comment] 2019-02-01 00:32
Confirmed fixed - thanks @mhart!

**Comment by debugwand** [comment] 2019-02-01 10:10
thanks very much for such quick work 🥇
